services:
  db:
    image: postgres:16-alpine
    container_name: cadastro_escola_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - my-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d school-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  my-network:
    driver: bridge

